"""Add owner column to items table

Revision ID: e18b1ce75853
Revises: a4e425f4f483
Create Date: 2025-08-05 01:13:15.840104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e18b1ce75853'
down_revision: Union[str, Sequence[str], None] = 'a4e425f4f483'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('owner', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'owner')
    # ### end Alembic commands ###
